Reimagined

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -3,9 +3,19 @@ name: 01 - Building Blocks
 on: push
 
 jobs:
-  echo-hello:
-    runs-on: ubuntu-latest
-    steps:
-     -name: Say hello
-      run: echo "Hello, World!"
+    echo-hello:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Say hello
+              run: echo "Hello, World!"
+    echo-goodbye:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Failed Step
+              run: |
+                echo "Step failed"
+                exit 1
+            - name: Say goodbye
+              run: echo "Goodbye"
+  
 
